version: '2'
services:
  xe18:
    image: gvenzl/oracle-xe
      #    build: ./docker-oracle-xe
    ports:
        - "1521:1521"
        - "5500:5500"
    volumes:
        -  "./oracle-xe-data:/opt/oracle/oradata"
    environment:
        - ORACLE_PWD=Oracle18
        - ORACLE_CHARACTERSET=AL32UTF8
        - ORACLE_EDITION=xe
        - ORACLE_SID=XE
  rstudio:
    image: rocker/rstudio
      #    build: ./orastudio
    ports:
        - "8787:8787"
    volumes:
        - "./rstudio-data:/home/rstudio"
    environment:
        - PASSWORD=Oracle18
