version: '2'
services:
  xe18:
    image: oracle-xe:18c
      #    build: ./docker-oracle-xe
    ports:
        - "1521:1521"
        - "5500:5500"
    volumes:
        -  "./oracle-xe-data:/opt/oracle/oradata"
  rstudio:
    image: orastudio
      #    build: ./orastudio
    ports:
        - "8787:8787"
    volumes:
        - "./rstudio-data:/home/rstudio"
    environment:
        - PASSWORD=Oracle18
